version: 0.1

phases:
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file app.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file post-app.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - post-app.yaml
    - index.js
  discard-paths: yes
